### ISSUE TITLE
POSIX equivalent of isatty

### ISSUE THREAD

**Issue by craigbarnes** [ThomasDickey/misc_tools-snapshots#1]
Hi. I noticed the following statement in the [documentation](https://invisible-island.net/misc_tools/index.html) for `isatty`:

> While I am aware that some variations of Bourne shell provide a way to do this, nothing like that appears in the [standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html).

As far as I can tell, [`test -t`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html) has been the standard way of doing this from the command-line since at least POSIX '98 (issue 5).

The following is more or less equivalent to the `isatty` program:

```sh
test -t 0 -a -t 1
```

**Comment by ThomasDickey** [comment]
Thanks for the feedback (I'll make a to-do to amend that comment).
